---
- hosts: all

  vars_prompt:
    - name: user_name
      prompt: "Enter your linux user name"
      private: no

  tasks:
    - name: Set keyboard layout
      shell: localectl set-x11-keymap de
      tags:
        - localectl

    - name: Add user aur_builder
      user:
        name: aur_builder
      tags:
        - aur_builder

    - name: Allow aur_builder to run sudo on pacman without PW
      lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        state: present
        line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
        validate: /usr/sbin/visudo -cf %s
        create: yes
      tags:
        - aur_builder

    - name: Git clone yay
      git:
        repo: https://aur.archlinux.org/yay.git
        dest: ~/yay
        version: master
        accept_hostkey: yes
      become: yes
      become_user: aur_builder
      tags:
        - yay

    - name: Install yay
      shell: makepkg -si --noconfirm
      become: yes
      become_user: aur_builder
      args:
        chdir: ~/yay
      tags:
        - yay

    - name: Install visual-studio-code
      shell: yay -S visual-studio-code-insiders-bin --noconfirm
      become: yes
      become_user: aur_builder
      tags:
        - yay

    - name: copy background picture
      copy:
        src: ./files/wallpaper.jpg
        dest: /home/{{ user_name }}/.config/wallpaper.jpg
        owner: "1000"
        group: "1000"
        mode: 0644

    - name: copy ~/.Xresources
      copy:
        src: ./files/Xresources
        dest: /home/{{ user_name }}/.Xresources
        owner: "1000"
        group: "1000"
        mode: 0644

    - name: Create i3status config directory
      shell: pacman -S picom xf86-video-intel --noconfirm
      become: yes
      tags:
        - graphics

    - name: Create i3status config directory
      shell: mkdir -p /home/{{ user_name }}/.config/i3status
      tags:
        - i3config

    - name: copy ~/.config/i3/config
      copy:
        src: ./files/i3config
        dest: /home/{{ user_name }}/.config/i3/config
        owner: "1000"
        group: "1000"
        mode: 0644

    - name: copy ~/.config/i3status/i3status.conf
      copy:
        src: ./files/i3status.conf
        dest: /home/{{ user_name }}/.config/i3status/i3status.conf
        owner: "1000"
        group: "1000"
        mode: 0644

    - name: Create BTRFS Snapshot of root /
      shell: btrfs sub snap / /.snapshots/TESTING > /dev/null 2>&1
      become: yes
      tags:
        - graphics
# 1) Zertifikate

# 2) Scaling
